### PR TITLE
Rewrite cifar-10_convnet to use new features

### PR DESCRIPTION
**Pull request by hunse**
- Work with newest versions of Nengo, NengoDL, NengoLoihi.
- Use `nengo.transforms.Convolution` to describe network more easily.
- Use NengoLoihi's `block_shape` to automatically split large
  ensembles and put things on the chip easily.
- Add more detailed descriptions of what's going on in each step.

Supersedes #22.

### CODE REVIEW

**Comment by hunse** [comment]
I made the `cifar10-rewrite-history` branch to store the history of this; it can be deleted when this is merged.

**Comment by hunse** [comment]
I just noticed that `checkpoint_base` should probably be "cifar10_convnet_params" not "cifar10_convnet_nengo_params".

**Comment by hunse** [comment]
Fixed those cut-off sentences. In your changes, you removed where I pre-set the name for all layers. I did this so that the names would be the same if we loop through `layer_confs`; in fact, I think the way it is now should give an error when we try to get the name later.

However, I'm running into a problem on my machine where `np.array(tf.one_hot(train_x, 10))` doesn't work, because `one_hot` returns a symbolic tensor that can't be converted to a Numpy array. I'm on TensorFlow 2.0. Any ideas how to fix this?

Otherwise, the changes look good.

**Comment by hunse** [comment]
So I was on an older version of NengoDL accidentally, and somehow that broke the `tf.one_hot`. Maybe it was changing the eager execution stuff or something. Anyway, it works now that I switched back.

Also, I forgot that we were naming all the layers now, which is why it's not a problem. I just got rid of the default for "name", since if anyone didn't specify a name for a layer I think it would be a problem.

**Comment by drasmuss** [comment]
> In your changes, you removed where I pre-set the name for all layers. I did this so that the names would be the same if we loop through layer_confs; in fact, I think the way it is now should give an error when we try to get the name later.

Ah yeah I didn't see it being used farther down as well. What do you think about just removing the default (since it's specified in all the configs anyway)? I mainly just wanted to avoid the extra clutter in the code and text, since it's a relatively unimportant part of what's going on in this notebook.

> However, I'm running into a problem on my machine where np.array(tf.one_hot(train_x, 10)) doesn't work, because one_hot returns a symbolic tensor that can't be converted to a Numpy array. I'm on TensorFlow 2.0. Any ideas how to fix this?

What if you do `tf.one_hot(...).numpy()` instead of `np.array(...)`? I'm not sure what would have changed that that would suddenly stop working for you though.

**Comment by drasmuss** [comment]
Fixups look good to me, will move this over to Nengo Loihi now.

**Comment by drasmuss** [comment]
PR up at https://github.com/nengo/nengo-loihi/pull/282

**Pull request closed without merging**
