### PR TITLE
Added examples for thresholding and SPA

### PR DESCRIPTION
**Pull request by Seanny123**
Some quick examples using the Nengo GUI that I created as a result of some email correspondence.

### CODE REVIEW

**Comment by tbekolay** [comment]
The core examples look empty to me?

**Comment by Seanny123** [comment]
Fixed that.

**Comment by jgosmann** [comment]
The thresholding example LGTM.
It might be good to have some plots already opened for the SPA compare example (and maybe some more comments)? Also, I'm not sure how I feel about adding new SPA examples given the refactoring ... (once nengo/nengo#1137 finally moves forward, still waiting for reviews). At least the `inputA` and `inputB` names will change to `input_a` and `input_b`.

**Review by tbekolay — APPROVED** [review]
I removed the SPA example because it uses the deprecated `nengo.spa` module rather than NengoSPA and converted the thresholding example to an notebook. Merging.

**Pull request merged**
